### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'Currency.ConvertedPrices.TransactionId' in 'field list'

### ISSUE THREAD

**Issue by nicolabortignon** [TracklistMe/server#37]
After https://github.com/TracklistMe/server/commit/52885fd2e83f5559116e7658ecbf5b2807e1ae95
accessing http://localhost:9000/#/music/release/232

generates this stack error in the server:

Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Currency.ConvertedPrices.TransactionId' in 'field list'
    at module.exports.Query.formatError (/Users/bortignon/tracklistme/server/node_modules/sequelize/lib/dialects/mysql/query.js:157:16)
    at Query._callback (/Users/bortignon/tracklistme/server/node_modules/sequelize/lib/dialects/mysql/query.js:35:23)
    at Query.Sequence.end (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/bortignon/tracklistme/server/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

And this in the client: 

angular.js:11707 TypeError: Cannot read property '1' of null
    at getConvertedPrice (ngCart.js:142)
    at $parseFunctionCall (angular.js:12456)
    at Object.expressionInputWatch (angular.js:12865)
    at Scope.$get.Scope.$digest (angular.js:14389)
    at Scope.$get.Scope.$apply (angular.js:14660)
    at done (angular.js:9734)
    at completeRequest (angular.js:9924)
    at XMLHttpRequest.requestLoaded (angular.js:9865)

**Comment by mziccard** [comment]
Closed with 2fc605eed7ade9a9cf060da3cf964af5b1ea1b06
